### ISSUE TITLE
Laravel sms integration with beem Africa. 

### ISSUE THREAD

**Issue by Jijiri89** [bryceandy/laravel-beem#3]
Please, I followed your instructions to integrate but I got stuck.
What I need is that,
I want a to create ui to display the form where I can enter the name of the user I want to send to, the body of the message and the sechudeled date.
How do I link this to any model I want to use for this. Thanks

**Comment by bryceandy** [comment]
You can create your form data how you want, all you need is the recipient's phone number to send an SMS [as seen in the documentation](https://github.com/bryceandy/laravel-beem#1-sms)

Please use this section to report issues found in the package, stating clearly what you did in your code and the resulting errors you are facing. For questions add a topic in the discussions.
